// <auto-generated />
namespace PhotoServer.DataAccessLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdjustPhotoFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdjustPhotoFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201305250337150_AdjustPhotoFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
