// <auto-generated />
namespace PhotoServer.DataAccessLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MakePhotoFieldsNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakePhotoFieldsNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201305252136028_MakePhotoFieldsNullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
